### ISSUE TITLE
Issue-feat: Added SBT features

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-contract#10]
Automated Review Comments
Issues in Review-SBT.sol:
  - (30, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
