### ISSUE TITLE
Issue-Create Profile-SBT.sol

Added profile SBT contract

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-contract#16]
Automated Review Comments
Issues in Profile-SBT.sol:
  - (17, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
