### ISSUE TITLE
Issue-Create company-nft.sol

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-contract#2]
Automated Review Comments
Issues in company-nft.sol:
  - (19, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
