### ISSUE TITLE
Issue-Update company-nft.sol

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-contract#4]
Automated Review Comments
Issues in company-nft.sol:
  - (14, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
