### ISSUE TITLE
Issue-Create Review-SBT.sol

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-contract#8]
Automated Review Comments
Issues in Review-SBT.sol:
  - (33, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')

**Comment by williamddobson3** [comment]
I got it.
